import type { Metadata } from "next";
import Header from './components/Header'
import Nav from './components/Nav'
import { options, auth } from './api/auth/[...nextauth]/options';
import "./globals.css";


export const metadata: Metadata = {
  title: "Dcard Intern",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  // const session = await getServerSession(options)
  const session = await auth()
  return (
    <html lang="en">
      <body className='bg-bodycolor'>
        <Header user={session?.user}/>
        <Nav />
        {children}
      </body>
    </html>
  );
}
