import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from './components/Header'
import Nav from './components/Nav'
import { options } from './api/auth/[...nextauth]/options';
import { getServerSession } from 'next-auth';
import "./globals.css";


export const metadata: Metadata = {
  title: "Dcard Intern",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  const session = await getServerSession(options)
  return (
    <html lang="en">
      <body className='bg-bodycolor'>
        <Header user={session?.user}/>
        <Nav />
        {children}
      </body>
    </html>
  );
}
